algoritmo "3"
var
   y: inteiro
Procedimento gerador (a: caractere; b:inteiro)
inicio
      Escreval ("+-------=======------+")
      Repita
            Escreval (" Aprendendo Portugol")
            b <- b-1
      Ate (b = 0)
      Escreva ("+-------=======------+")
FimProcedimento
inicio
      Escreva ("Quantas vezes repetir? ")
      Leia (y)
      gerador ("Aprendendo Portugol",y)
fimalgoritmo
