algoritmo "Soma com Procediemnto"   // Passagem de Paraâmetoro (TIpo 1)
// Função :
// Autor :
// Data : 13/02/2021
// Seção de Declarações
var
   x,y: inteiro
Procedimento Soma (a,b: inteiro)
inicio
      Escreval ("Recebi o valor: ",a)
      Escreval ("Recebi o valor: ",b)
      Escreval ("A soma entre os valores é: ", a+b)
FimProcedimento
inicio
      x <- 5
      y <- 3
      Soma (x,y)
fimalgoritmo
